services:
  db:
    image: postgres:17
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 10s
      retries: 5

  api:
    build: .
    container_name: my_api
    command: [ "sh", "-c", "/authSrvcMigrate && /authSrvc" ]
    depends_on:
      db:
        condition: service_healthy
    environment:
      PG_URL: "postgres://${PG_USER}:${PG_PASS}@db:5432/${PG_DB}?sslmode=disable"
    ports:
      - "8080:8080"

volumes:
  postgres_data: