http:
  port: "8080"
  host: "0.0.0.0"

logger:
  log_level: "debug"

auth:
  signing_key: "qqvgfg5jk3fwioi2ifsd"
  accessttl: 15m
  refreshttl: 1440m

pg:
  pg_url: "postgres://postgres:qwerty@localhost:5432/postgres?sslmode=disable"

app:
  dev_mod: true
  webhook_url: ""