http:
  port: "8080"
  host: "127.0.0.1"

logger:
  log_level: "debug"

auth:
  signing_key: "qqvgfg5jk3fwioi2ifsd"
  accessttl: 15m
  refreshttl: 1440m

pg:
  pg_url: "postgres:qwerty@localhost:5432/postgres?sslmode=disable"
  schema_url: "migrations"